{
 "title": "Fraud Detection Realtime",
 "tags": [
  "fraud",
  "spark",
  "kafka"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Throughput msgs/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(kafka_messages_consumed_total[5s])"
    }
   ]
  },
  {
   "title": "Processing latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "spark_processing_latency_ms" }
   ]
  },
  {
   "title": "Inference latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(model_inference_latency_ms_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(model_inference_latency_ms_bucket[1m])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Fraud ratio % (last 1m)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 * (sum_over_time(predictions_total{label=\"fraud\"}[1m])) / clamp_min(sum_over_time(predictions_total[1m]), 1)"
    }
   ]
  }
 ]
}